const schouwburg = [
  //Global
  {
    type: 'disarm_stop',
    location: 'global',
    command: 'disarm_stop',
    label: 'Disarm en stop all',
    numbers: [51, 51, 150, 151]
  },
  {
    number: 0,
    location: 'global',
    type: 'groupStatus',
    command: 'group',
    isGroup: true,
    label: 'Actieve bel DE zaal',
  },
  {
    number: 100,
    location: 'global',
    type: 'groupStatus',
    command: 'group',
    isGroup: true,
    label: 'Actieve bel BZ zaal',
  },

  //DE zaal
  {
    number: 1,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 20:00',
  },
  {
    number: 2,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 19:00',
  },
  {
    number: 3,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 15:00',
  },
  {
    number: 4,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 14:00',
  },
  {
    number: 7,
    location: 'DE',
    type: 'group',
    command: 'play',
    label: 'DE zaal 5 bellen',
  },
  {
    number: 6,
    location: 'DE',
    type: 'cue',
    command: 'playPrewait',
    label: 'Pauze (20 minuten bel)',
  },
  {
    number: 5,
    location: 'DE',
    type: 'preWait',
    command: 'preWait',
    label: 'Start bel over <x> Minuten',
  },
  {
    number: 50,
    location: 'DE',
    type: 'disarm',
    command: 'play',
    label: 'Disarm DE Zaal',
  },
  {
    number: 51,
    location: 'DE',
    type: 'stop',
    command: 'play',
    label: 'Stop DE Zaal',
  },
  {
    number: 8,
    location: 'DE',
    type: 'cue',
    command: 'play',
    label: 'Losse bel',
  },
  {
    number: 9,
    location: 'DE',
    type: 'cue',
    command: 'play',
    label: 'Festival'
  },
  //Blauwe zaal
  {
    number: 101,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 20:30',
  },
  {
    number: 102,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 19:30',
  },
  {
    number: 103,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 16:00',
  },
  {
    number: 104,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 13:00',
  },
  {
    number: 107,
    location: 'BZ',
    type: 'group',
    command: 'play',
    label: 'BZ zaal 5 bellen',
  },
  {
    number: 106,
    location: 'BZ',
    type: 'cue',
    command: 'playPrewait',
    label: 'Pauze (20 minuten bel)',
  },
  {
    number: 105,
    location: 'BZ',
    type: 'preWait',
    command: 'preWait',
    label: 'Start bel over <x> Minuten',
  },
  {
    number: 150,
    location: 'BZ',
    type: 'disarm',
    command: 'play',
    label: 'Disarm Blauwe Zaal',
  },
  {
    number: 151,
    location: 'BZ',
    type: 'stop',
    command: 'play',
    label: 'Stop Blauwe Zaal',
  },
  {
    number: 108,
    location: 'BZ',
    type: 'cue',
    command: 'play',
    label: 'Losse bel',
  },
  {
    number: 109,
    location: 'BZ',
    type: 'cue',
    command: 'play',
    label: 'Festival'
  },
];

module.exports = schouwburg;
