const schouwburg = [
  //Global
  {
    type: 'disarm_stop',
    location: 'global',
    command: 'disarm_stop',
    label: 'Disarm en stop all',
    numbers: [7, 8, 17, 18]
  },
  {
    number: 101,
    location: 'global',
    type: 'cue',
    command: 'play',
    label: 'Bel DE',
  },
  {
    number: 102,
    location: 'global',
    type: 'cue',
    command: 'play',
    label: 'Bel BZ',
  },
  //DE zaal
  {
    number: 1,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 20:00',
  },
  {
    number: 2,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 19:00',
  },
  {
    number: 3,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 15:00',
  },
  {
    number: 4,
    location: 'DE',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 14:00',
  },
  {
    number: 6,
    location: 'DE',
    type: 'cue',
    command: 'playPrewait',
    label: 'Pauze (20 minuten bel)',
  },
  {
    number: 5,
    location: 'DE',
    type: 'preWait',
    command: 'preWait',
    label: 'Start bel over <x> Minuten',
  },
  {
    number: 101,
    location: 'DE',
    type: 'cue',
    command: 'play',
    label: 'Losse bel',
  },
  {
    number: 7,
    location: 'DE',
    type: 'disarm',
    command: 'play',
    label: 'Disarm DE Zaal',
  },
  {
    number: 8,
    location: 'DE',
    type: 'stop',
    command: 'play',
    label: 'Stop DE Zaal',
  },
  //Blauwe zaal
  {
    number: 11,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 20:30',
  },
  {
    number: 12,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 19:30',
  },
  {
    number: 13,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 16:00',
  },
  {
    number: 14,
    location: 'BZ',
    type: 'group',
    command: 'arm',
    label: 'Voorstelling 13:00',
  },
  {
    number: 16,
    location: 'BZ',
    type: 'cue',
    command: 'playPrewait',
    label: 'Pauze (20 minuten bel)',
  },
  {
    number: 15,
    location: 'BZ',
    type: 'preWait',
    command: 'preWait',
    label: 'Start bel over <x> Minuten',
  },
  {
    number: 102,
    location: 'BZ',
    type: 'cue',
    command: 'play',
    label: 'Losse bel',
  },
  {
    number: 17,
    location: 'BZ',
    type: 'disarm',
    command: 'play',
    label: 'Disarm Blauwe Zaal',
  },
  {
    number: 18,
    location: 'BZ',
    type: 'stop',
    command: 'play',
    label: 'Stop Blauwe Zaal',
  },
];

module.exports = schouwburg;
